### ISSUE TITLE
Secondary decays

### ISSUE THREAD

**Issue by jackfrost373** [jackfrost373/LcAnalysis_Simon#10]
We had a quick look at the IPchi2 distribution in MC of prompt vs secondary (beauty2charm). Aleksei worries that there are many different sources, and the fraction can actually be quite large (up to 20%?). There might be a different variable to look at here, the Transverse IP (TIP). 
- [x]  to attend the charm meeting on TIP. Check potential. Add TIP variable to nTuples ( @jackfrost373 )
- [x]  Make comparison plot of TIP in Lc signal MC vs Lb -> Lc MC ( @cpawley )

**Comment by cpawley** [comment]
Chris to plot in log scale and then send it to Simon

**Comment by cpawley** [comment]
Simon to plot IPChi2 (from MC prompt vs 2ndary) with abs cuts (linear and log scale)
