### ISSUE TITLE
[TBC] MC Simulations Redo for Dalitz

### ISSUE THREAD

**Issue by cpawley** [jackfrost373/LcAnalysis_Simon#29]
To be decided - ask for a new simulation using the New Lc -> pKpi 

Would be on request

**Comment by jackfrost373** [comment]
Update: jobs for the new run2 MC, coming from the Turbo, might have enough stats to not have to request new MC.

**Comment by jackfrost373** [comment]
-- this is now part of the general "new MC request" issue ( https://github.com/jackfrost373/LcAnalysis_Simon/issues/41 ), so closing it to avoid duplication.

(regarding the last comment: it seems Turbo MC does not have enough stats after all..)
