### ISSUE TITLE
MC-Data comparison

### ISSUE THREAD

**Issue by jackfrost373** [jackfrost373/LcAnalysis_Simon#49]
- [ ] make plots with MC vs sWeighed data
- [ ] devise MC-Data weighing strategy

**Comment by cpawley** [comment]
Was it intended to close this?

**Comment by jackfrost373** [comment]
> Was it intended to close this?

Yes, as it was already contained inside https://github.com/jackfrost373/LcAnalysis_Simon/issues/23 which I didn't see..
