### ISSUE TITLE
use DecayTreeFitter

### ISSUE THREAD

**Issue by jackfrost373** [jackfrost373/LcAnalysis_Simon#6]
Use the DecayTreeFitted (DTF) variables for IPchi2 and lifetime, for the comparison plots. These are much more powerful, due to the re-fit with vertex constraints.

**Comment by jackfrost373** [comment]
(Already in the nTuples)

**Comment by cpawley** [comment]
Simon has plot of DTF_CTau -> needs new axis labels (!). @jackfrost373 to provide with units.

**Comment by jackfrost373** [comment]
- ctau is calculated as "BPVLTIME()*c_light" according to https://twiki.cern.ch/twiki/bin/view/LHCb/BenderTutorialV23 . 
- BPVLTIME LoKi functor has description "_BPVLTIME: the proper lifetime of the particle. The functor evaluates the proper lifetime of the particle using ILifetimeFitter tool. Unfortunately due to very sad conventions adopted for LHCb, the proper time is measured in ns instead of the natural units, [ctau]_", according to https://twiki.cern.ch/twiki/bin/view/LHCb/LoKiHybridFilters#BPVLTIME_the_proper_lifetime_of

So the assumption we had that it is [mm] seems reasonable

**Comment by jackfrost373** [comment]
(also, the normal 'lifetime' is in [ns]).
