### ISSUE TITLE
Choose a trigger line

### ISSUE THREAD

**Issue by jackfrost373** [jackfrost373/LcAnalysis_Simon#9]
We did not make a trigger selection yet, but we need to in order to be able to determine it’s efficiency. Aleksei is worried that it might affect our Xi_c signal yield a lot. In addition, it seems from previous studies by Aleksei that at low p_T, the efficiencies for Xi_c and L_c are different. We will have to study this. In addition, the Xi_c upper sideband structure in momentum might disappear after we select a trigger line. (tightening PID did not seem to affect it).

**Comment by jackfrost373** [comment]
Hlt2: this makes selections on the flight distance chi^2. However, since Xi_c and L_c have different lifetimes, this could cause the Hlt2 trigger to have a different efficiency. Previous studies only considered 2011/2012 data, so will need to be investigated.

**Comment by jackfrost373** [comment]
We need to choose a stripping line, in order to determine the efficiency properly. The fear is that we will lose a lot of Xi_c signal candidates.
- [ ] Add the Run2 Hlt1 stripping line (Hlt1TrackMVA) to the nTuples ( @jackfrost373 )
- [ ] Check the efficiency of selecting the L0/Hlt1/Hlt2 TOS in MC (@SimonCalo )

**Comment by cpawley** [comment]
Add

L0 Hadron
HLT1 TrackAll_TOS
HLT2 Charm ....

**Comment by jackfrost373** [comment]
Just to add to the above: I'm adding the right trigger lines to the ntuples now. We should then add the 'trigger selection' to the default offline selection from now on. Also, as indicated above, we should test the efficiency of the trigger selection steps on MC (so no preselection, just MCMatching, and test L0 w.r.t. nothing, Hlt1 w.r.t. L0, and Hlt2 w.r.t. (Hlt1 & L0).

Selection L0:
- Naively, 'Lc_L0HadronDecision_TOS'. However, L0Hadron is a bit uncertain in determining its efficiency.
- We could follow the Lc paper and trigger on the rest of the event with the leptonic lines, e.g. 'Lc_L0ElectronDecision_TIS || Lc_L0MuonDecision_TIS'. We might loose to much Xi_c events with this though. I propose we see the efficiency of Xi_c in MC for both options.

Selection Hlt1:
- for 2011/2012 (Run1): 'Lc_Hlt1TrackAllL0Decision_TOS'
- for 2015-2018 (Run2): 'Lc_Hlt1TrackMVADecision_TOS'

Selection Hlt2:
- 'Lc_Hlt2CharmHadD2HHHDecision_TOS'

**Comment by SimonCalo** [comment]
So just to make sure, I need to wait for the new ntuples to apply check the efficiencies on the "new" trigger lines, correct?

**Comment by jackfrost373** [comment]
Correct! But they are done now. (jobs 29 and 30 are Lc and Xic MC with the right trigger line information).

**Comment by SimonCalo** [comment]
The selections with the new trigger lines decrease the number of events very heavily. However, everything that was indicated has been plotted.

**Comment by jackfrost373** [comment]
We chose L0Hadron_TOS, Hlt1TrackAllL0_TOS (run1) or Hlt1TrackMVA_TOS (run2), and Hlt2CharmHadD2HHH_TOS
